# Doing request 
# Consuming open source APIs
# import requests module

#import requests
#response  = requests.get("https://datausa.io/api/data?drilldowns=Nation&measures=Population")
#print(response) # Get 200 as response for a correct Request.
#print(response.json()) # Print JSON data from the requested URL

# Getting Data from Sigfox Backened using API.


# import requests

# login = "username"
# password = "loginpassword"
# authentication = (login, password)
# response = requests.get("https://api.sigfox.com/v2/devices/device-ID/messages",auth=authentication) 

# print(response)

# # The variable response contains the response from the server

import requests
import requests
from requests.auth import HTTPBasicAuth
import base64
import time

url = "https://api.sigfox.com/v2/devices/79C030/messages"

#SOLUTION 1
#using a token
#the token is generated by encoding login:password in Base 64
print("----TOKEN----")
login = '63f7ce5c33d968201d7f4e45'
password = '0aa5beba30af812055c135f9fe6b5c6d'
token = login+":"+password
print("Token:", base64.b64encode(token.encode("ascii")).decode("ascii"))
print()

#Once the token is generated, you can use the token directly in your code, it is safer in case your code leaks.
print("----SOLUTION 1----")
headers = {
  'Authorization': 'Basic NjNmN2NlNWMzM2Q5NjgyMDFkN2Y0ZTQ1OjBhYTViZWJhMzBhZjgxMjA1NWMxMzVmOWZlNmI1YzZk'
}
response = requests.get(url, headers=headers)
print(response.text)
print()

time.sleep(2) #just because I do 2 API requests in a row, Sigfox limits to 1 request per second, so I need to slow my strict down

